/* Automatically generated by './build/bin/build-entry.js' */

import Button from './components/button/index';
import Checkbox from './components/Checkbox/index';
import Checkgroup from './components/Checkgroup/index';
import Input from './components/Input/index';
import Link from './components/Link/index';
import Number from './components/Number/index';
import Radio from './components/Radio/index';
import Prog from './components/prog/index';
import Swi from './components/Swi/index'
import Select from './components/select/index'
import Upload from './components/upload/index'
const components = [
  Upload,
  Select,
  Swi,
  Prog,
  Button,
  Checkbox,
  Checkgroup,
  Input,
  Link,
  Number,
  Radio,
];
const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

export default {
 install,
 Button,
 Checkbox,
 Checkgroup,
 Input,
 Link,
 Number,
 Radio,
 Select,
 Swi,
 Prog,
 Upload
};